### ISSUE TITLE
使用上的小問題

### ISSUE THREAD

**Issue by LianSheng197** [ngseke/leetcode-night#19]
1. 在 Readme 裡的截圖，擴充元件的底色是黑色的，但是我看到的都是白色...
    對此我找不到相關設定的選項。請見附圖：
    ![Selection_247](https://user-images.githubusercontent.com/18535495/164989141-9ffc746c-663a-40fc-b12c-790a163cfcff.png)

2. 從題目清單進入題目詳細頁面時，有時候會閃一下白色才轉黑。  
    我不確定是什麼環節出了問題，如果能修的話就太好了 :+1: 
    （使用瀏覽器：`Chrome 99.0.4844.51`）

3. Chrome 擴充元件商店裡的版本還在 `0.0.4`

---
最後提個不相干的，那個吉祥物有夠ㄎㄧㄤ，可是我喜歡XD

**Comment by ngseke** [comment]
@lxieyang 

> 1. 在 Readme 裡的截圖，擴充元件的底色是黑色的，但是我看到的都是白色...
>    對此我找不到相關設定的選項。請見附圖：

這個擴充功能的組件是來自 [Tocas UI](https://v4.tocas-ui.com/zh-tw/colors.html)，但我並沒有特別指定 `[data-scheme="dark"]`，所以它其實是根據使用者的裝置，自動決定套用亮色或暗色的主題。

> 2. 從題目清單進入題目詳細頁面時，有時候會閃一下白色才轉黑。
>    我不確定是什麼環節出了問題，如果能修的話就太好了 👍
>    （使用瀏覽器：`Chrome 99.0.4844.51`）

我似乎無法復現你描述的情況，可以的話請提供更多細節。

> 3. Chrome 擴充元件商店裡的版本還在 `0.0.4`

通常 release 新版本後我會同步在商店提交審查，所以目前在等審查通過。

> 最後提個不相干的，那個吉祥物有夠ㄎㄧㄤ，可是我喜歡XD

謝啦🐱👍

**Comment by LianSheng197** [comment]
> 這個擴充功能的組件是來自 [Tocas UI](https://v4.tocas-ui.com/zh-tw/colors.html)，但我並沒有特別指定 [data-scheme="dark"]，所以它其實是根據使用者的裝置，自動決定套用亮色或暗色的主題。

其實我就是從 Tocas 看到這個專案的，它很神奇地出現在專案旁邊的 `Used by`  
至於亮色或暗色的主題，可以敲碗之後新增一個選項方便切換嗎 :heart_eyes_cat: 

> 我似乎無法復現你描述的情況，可以的話請提供更多細節。

我不確定有沒有辦法抓到問題，不過這陣子我會多留意點。

**Comment by ngseke** [comment]
那麼我應該會考慮讓 Popup 永遠套用暗色主題。
因為我在想如果再加一個切換功能，可能會和切換 LeetCode 本身的深色模式混淆。

**Comment by LianSheng197** [comment]
聽起來不錯，感謝 :+1:
